### ISSUE TITLE
OAuth issue

### ISSUE THREAD

**Issue by sbrooke** [python-wink/python-wink#110]
I might be using this in an atypical way so it could be the source of my problem.  I'm not integrating with HA, only running the sample code from the cli.  The sample code requires copying and pasting a URL into a browser, logging into the Wink account and then copying the returned code (only) out of the response URL.  Does anyone have a sample where the credentials can be fed in through Python and the response code automatically parsed?

**Comment by w1ll1am23** [comment]
You can try running the process and inputting the code then the next time just call def set_wink_credentials(client_id, client_secret, access_token, refresh_token) you would have to get the refresh token from the debug logs, or put in some prints but I think it should work. Then in your script or whatever pull the token/refresh token from a config file and feed it to this method every time?

**Comment by sbrooke** [comment]
Ok, I can look at that, but where do the debug logs land?

**Comment by w1ll1am23** [comment]
Try adding this to whatever script you have

```
import logging
import sys

root = logging.getLogger()
root.setLevel(logging.DEBUG)

ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
root.addHandler(ch)
```

This will make it log to the console.

**Comment by sbrooke** [comment]
That supplied more output but didn't provide the code.  It did show the refresh token after doing the login and copying and pasting the returned code.  So, maybe a step in the right direction, but how can I show the returned URL with the code in it from a debug log?

**Comment by w1ll1am23** [comment]
There is no easy way to do that, you would have to be running a webserver via your script that catches the redirect URL. The code process only needs to be run 1 time in order to obtain the tokens. (Home Assistant only calls the code method once when you setup Wink and then isn't used again.) Once you have the tokens you won't need to run it again. The only reason I see for needing that would be to make it easier for other to use your script/program i.e. like HomeAssistant. 

Maybe explaining what you are trying to do will help me explain the best way for you to do this.

**Comment by sbrooke** [comment]
I want to grab temperature and humidity from sensors and feed that to an InfluxDB for displaying in Grafana.  I think I see what you're saying.  There needs to be a process for authorizing with the code the first time, but then the access_token and refresh_token are stored and called for subsequent requests?

**Comment by w1ll1am23** [comment]
Correct. Also, Home Assistant supports influx https://www.home-assistant.io/components/influxdb/ so maybe it would be easier to just use that?

**Comment by sbrooke** [comment]
I'm also trying to learn a bit more about Python, but I'll take a look at that integration for what I need.  Thanks for all your help!

**Comment by w1ll1am23** [comment]
No problem! So can this issue be closed?

Also feel free to reach out on discord if you need more help, I am w1ll1am on there.

**Comment by sbrooke** [comment]
Yes, thanks again!
