### ISSUE TITLE
Spotters read only as open / closed

### ISSUE THREAD

**Issue by TDWhbp** [python-wink/python-wink#13]
I have a pair of spotters in my Wink system when using Home assistant they only show as open/ closed normally closed. 
![haspotters](https://cloud.githubusercontent.com/assets/12042563/12386026/bbc7edd2-bd8f-11e5-8927-8bd1ca95345c.png)
do I have something set wrong or is this an issue with the python-Wink?

**Comment by w1ll1am23** [comment]
What are you trying to achieve with the spotter? I know these are multi purpose sensors, but I assume they are getting picked up in python-wink as just a motion sensor. What all data do these return?

**Comment by TDWhbp** [comment]
the Data they return is Temperature, Humidity, Light, Vibration and Sound... they do not do motion detection. It would be awesome if I could at least view temperature and humidity.

**Comment by bradsk88** [comment]
I would be happy to add better support for that sensor.

Can you please go to the [Wink API Explorer](http://docs.wink.apiary.io/#reference/device/wink-devices/retrieve-all-devices-of-user?console=1) and copy and paste the body of `Retrieve All Devices of User` here.

---

If you've never used the API explorer, you just have to [go there](http://docs.wink.apiary.io/#reference/device/wink-devices/retrieve-all-devices-of-user?console=1) and add a new `Header` with the following key/value pair:
- `Authorization` `Bearer YOUR_WINK_ACCESS_TOKEN` 

... and press `Call Resource`

**Comment by TDWhbp** [comment]
here is the body... please remove this whenafter you are done it could have private info i missed thanks.
`Redacted at user's request`

**Comment by bradsk88** [comment]
Thanks @TDWhbp, I've saved a copy of that to use for expanding the functionality.  I may use snippets of it when building unit tests but I'll make sure to comb through carefully and replace the values with valid alternatives to protect your privacy.

**Comment by TDWhbp** [comment]
if you are having any issues with testing due to my edits I am willing to assist.

**Comment by w1ll1am23** [comment]
@bradsk88 I just picked up a spotter yesterday, so if you need anyone else to test, I can as well.

**Comment by TDWhbp** [comment]
has there been an update on this? could it be that I am just missing some input markers in Home assistant?

**Comment by bradsk88** [comment]
No progress yet. Sorry.  I've been busy with other obligations.

**Comment by bradsk88** [comment]
Going to try to get a solution for this pushed up and merged into http://github.com/balloob/home-assistant tomorrow night.  If I can't get it out then, I'll be off the grid for a little over a week.

**Comment by bradsk88** [comment]
Solution is out on pypitest

@w1ll1am23 I'd appreciate if you can install it and test to see if your devices still work, including the sensors.  All I currently have are light bulbs, which work.

You can test by installing via this command:

```
pip install -i https://testpypi.python.org/pypi --upgrade python-wink==0.6.0.3
```

Checkout http://github.com/balloob/home-assistant and update the `python-wink` requirements to use version `0.6.0.3`.  In that project, run `script/setup`, then run `hass` and go to `http://localhost:8123/`.

**Comment by TDWhbp** [comment]
@bradsk88  I tried to run the command listed and got 
`
Could not find a version that satisfies the requirement python-wink0.6.0.3 (from versions: )
No matching distribution found for python-wink0.6.0.3
`
belay my last... i ran 
`pip3 install -i https://testpypi.python.org/pypi --upgrade python-wink==0.6.0.3` with no issues

**Comment by TDWhbp** [comment]
ok, I got step 1 I do not understand step 2 could you help me out with a walk through I am running to many issues and as I like to say '-"instructions unclear cat now stuck in ceiling fan"-' ... I downloaded version .12 of HA but can't get setup to run locally

**Comment by bradsk88** [comment]
@TDWhbp No worries.  @w1ll1am23  was able to test for me.

I'll try to push up a guide for testing these kinds of things when I get back from vacation.

python-wink 0.6.0 is now available on pypi and offers support for all of the sensors inside the Quirky Spotter.  Just need to update https://github.com/balloob/home-assistant to make use of them.

Marking this resolved.
