### ISSUE TITLE
Wink App updates

### ISSUE THREAD

**Issue by TDWhbp** [python-wink/python-wink#18]
Wink App now allows Local control does this update change the way Python-wink will work?

**Comment by bradsk88** [comment]
Nothing should change on our end.  When I'm home from holiday, I'll be talking to the folks at Wink to get the information I'd need to allow for localhost control via python-wink.

**Comment by TDWhbp** [comment]
could you look into why the wink z-wave devices no longer work in HA? hope you have a great holiday

**Comment by ad8mustanggt** [comment]
For me, after the update, dimmer switches ("lights" in HA) work but on/off "switches" no longer work...

**Comment by TDWhbp** [comment]
sorry about closing reopening ... fat finger mistake.

@ad8mustanggt  are your dimmers zwave or zeebee? all my zeebee stuff works but for some reason the zwave stuff is broken.

**Comment by ad8mustanggt** [comment]
It's all zwave... Don't use any zeebee stuff.

**Comment by bradsk88** [comment]
Solution is in the pipes.  Just need to merge it out.

https://github.com/bradsk88/python-wink/pull/20

Sorry guys.  Things will calm down after 1.0.
