### ISSUE TITLE
Local Control

### ISSUE THREAD

**Issue by danielolson13** [python-wink/python-wink#22]
What is the status of being able to use the local control api?

**Comment by bradsk88** [comment]
Not yet.  I have some free time this week so I'll dig into it.

**Comment by danielolson13** [comment]
Great, thanks!

**Comment by bradsk88** [comment]
I'm waiting to get a response from Wink themselves.  I see the device on LAN but it won't accept commands so there must be an additional layer to get through.

They're usually pretty open about how their stuff works ... so fingers crossed.

**Comment by danielolson13** [comment]
It's looking for a bearer token to be set and I want to say it runs on port
8888.

It's great Wink has been so open.

**Comment by bradsk88** [comment]
Yeah, I hit it with a bearer token.
I'm somewhat concerned that the API endpoints on the device might not match the ones on api.wink.com

**Comment by danielolson13** [comment]
Yeah, you're right. I've poked at the local api and can get a list of
devices. I have root access but I can't figure it out. Hopefully they can
shed some light.

**Comment by bradsk88** [comment]
> At this time, we have not opened up local control for use by developers

:(

**Comment by mannkind** [comment]
I would love to see local control access. Getting the token is possible if you root the device OR get one via the V2 API with your credentials (supposedly, I'm still waiting for Wink to give me credentials to test this method). 

In the meantime they did send me info on the v2 API and I have a token because my device is rooted: http://docs.winkapiv2.apiary.io/

```
curl -k –include -H "Authorization: Bearer TOKEN_HERER" -H "Content-type: 'application/json'" https://winkhub:8888/light_bulbs/1
```
```
HTTP/1.1 200 OK
content-type: application/json
content-length: 285
Date: Sat, 02 Jul 2016 00:44:25 GMT
Connection: keep-alive

{"data":{"hub_device_id":"1","object_type":"hub_device","discovered_at":1466484777.436,"last_reading":{"connection":true,"powered":false},"desired_state":{},"local_id":1,"created_at":1466484776.77,"name":"New HA Dimmable Light","updated_at":1467352807.649},"errors":[],"pagination":{}}
```

**Comment by rbflurry** [comment]
+1 for this.

At this time it would only work for Rooted winks hubs, but would be great.

**Comment by bazhip** [comment]
@mannkind How were you able to get this to work? I'm on the newest firmware and I cannot for the life of me get it to respond. I just get an error 35 from curl about an unknown SSL protocol error??

I'm entering the curl command exactly as you've entered it (well save for the authorization token. I've also tried the examples from the README.md (which isn't there anymore on the newest version??) and I get the same curl error.

Did you (or anyone else) run into this problem? And if so, how did you solve it? I've wasted a couple hours on this and I've gotten nowhere. 

Also In the config.json, I already have an access token, but the permissions are blank. What should get put into the permission field?

Sorry for bugging you guys, but I figured no harm in asking.

**Comment by rbflurry** [comment]
The curl commands I was using is posted over here. https://community.home-assistant.io/t/rooted-wink-local-control/4733/8

Are you ignoring ssl errors since the wink hub uses an invalid certificate?

**Comment by bazhip** [comment]
I think so. I rarely use curl, so I might have the syntax wrong but from what I understand, shouldn't -k or --insecure do that? I've tried both and I've put them in every place possible, but still get that error lol. I'll try the commands from the HA site when I'm back home in a bit. I'm wondering if it has something to do with the machine I'm using? I was remoting in to a pi, so maybe there is something wrong with the SSL on it?

Would I get this problem if my bearer token is wrong? I know I manually modified it at one point. 

In my config.json the client_permissions value is blank. Is yours as well? If not, what should it be set at?

Are you able to bulk issue state changed through the local control? As of right now I'm using wink-mqtt, but I have like 15 lights in my house, so I send 15 separate mqtt messages and it takes quite a while to process them all.

This is working on the latest firmware, correct? 2.66?

EDIT: Just tried it from a different computer. Still error 35.

Thanks!

**Comment by mannkind** [comment]
@bazhip - Yup, it's the exact command I use from my RPi (maybe it's not perfect, but it works). 

Here is some info on my tools used on my RPi. 

```
uname -a
Linux themis 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

bash --version
GNU bash, version 4.3.30(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

curl --version
curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

The only thing I changed in my config.js file was the created_at and updated_at values to `2114380800.892` because I didn't want to deal with refreshing tokens. The client_permissions value is blank, even when the token was generated by the wink app. 

The wink app says v2.66.0

**Comment by bazhip** [comment]
I got it working!!

To anyone in the future with a similar problem:

I noticed the SHA-256 field was empty in config.json. I ended up regenerating the cert with the script in /opt/local_control and copying the new files over to /database/local_control/data. After that, I backed up config.json and deleted it. I restarted the localcontrol service and it generated a new config.json file which also contained the SHA-256. This still left the authorization token blank for some reason (didn't get regenerated). So, I copied the authorization token from the backup into the new one and restarted the service one more time and this time it was good to go!

Thanks for bearing with me!

**Comment by bazhip** [comment]
I think so. I rarely use curl, so I might have the syntax wrong but from
what I understand, shouldn't -k or --insecure do that? I've tried both and
I've put them in every place possible, but still get that error lol. I'll
try the commands from the HA site when I'm back home in a bit. I'm
wondering if it has something to do with the machine I'm using? I was
remoting in to a pi, so maybe there is something wrong with the SSL on it?

Oh one other thing: are you able to bulk issue state changed through the
local control? As of right now I'm using wink-mqtt, but I have like 15
lights in my house, so I send 15 separate mqtt messages and it takes quite
a while to process them all.

Lastly, this is working on the latest firmware, correct? 2.66?

Thanks!

On Oct 20, 2016 4:37 PM, "rbflurry" notifications@github.com wrote:

The curl commands I was using is posted over here. https://community.home-
assistant.io/t/rooted-wink-local-control/4733/8

Are you ignoring ssl errors since the wink hub uses an invalid certificate?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/python-wink/python-wink/issues/22#issuecomment-255235670,
or mute the thread

**Comment by asapkota** [comment]
curl -i -k -X GET "https://192.168.171.253:8888/devices" \
            -H "Authorization: Bearer $token"

replace $token with token. Works for me on 2.68

Have you guys figured out a way to control or get information of devices?

**Comment by asapkota** [comment]
I was able to get a valid response with this using python as well.

url = host + "devices"
requests.packages.urllib3.disable_warnings()
response = requests.get(url, headers={'Authorization' : 'Bearer ' + token}, verify=False)
print (response.status_code)
print (response.headers['content-type'])
print (response.json())

No luck with changing state though.

This gets a 200 response but does not do anything to the thermostat. Unfortunately I do not have a bulb to test.

url = host + "thermostats" + "/1"
requests.packages.urllib3.disable_warnings()

response = requests.put(url, headers={'Authorization': 'Bearer ' + token, 'Content-Type':  application/json'}, data=json.dumps({"desired_state":{"fan_mode": on}}), verify=False)

print (response.status_code)
print (response.headers['content-type'])
print (response.json())

**Comment by mannkind** [comment]
You should be able to use the same API found here - http://docs.winkapiv2.apiary.io/
At least it worked for me when controlling my lights.

**Comment by asapkota** [comment]
That's what I have been trying but no luck yet with thermostat.

I am trying to get "last_reading" states to show current temp on HASS but I
keep getting a syntax error or no such property error.

**Comment by rbflurry** [comment]
@asapkota I believe local control is only for lights and switches.

**Comment by asapkota** [comment]
Really? that sucks. I thought they exposed the local control api for all
devices.

Is there a way to run a aprond command directly from HASS?

**Comment by AppleTechy** [comment]
Can someone who has a rooted hub send me a dump of the data? My email address is in my bio or github.  Trying to figure out how the the local access bearer pin is encrypted. I have found the API call to get the hash, but I don't know how to decrypt. And I want to make sure the hash is actually the bearer token as it isn't exactly said, what the hash is used for other than "local public hash".

**Comment by AppleTechy** [comment]
@bazhip Do you still have a rooted hub that you could send me a dump of? The php code? Look at my above comment if you need more info.

**Comment by bazhip** [comment]
The latest firmware? There's no more PHP. It's all node. If you want one
with PHP, it's not going to have the local control API on there.

**Comment by AppleTechy** [comment]
@bazhip Do you have access to the node dump? That would be extremely helpful. Trying to figure out its naming scheme since the API rarely has the name assigned to it in their App. So I am trying to find out how it's assigning names to numbers...

**Comment by AppleTechy** [comment]
Also has anyone figured out how Wink is generating nonces?

**Comment by rbflurry** [comment]
@asapkota I did some testing using aprond over SSH to my wink hub (its rooted)

But the time it took to setup a SSH session with every command was not the quickest or most reliable.

**Comment by w1ll1am23** [comment]
Added in #76
