### ISSUE TITLE
Support for Color Temperature in Commercial Electric Smart LED Downlight

### ISSUE THREAD

**Issue by henrikraken** [python-wink/python-wink#38]
I am working on getting the commercial Electric Smart LED Downlights working. Currently, they are automatically discovered in HomeAssistant with the Wink hub, can be dimmed, can be turned on and off, but cannot be adjusted in the color temperature.  http://www.wink.com/products/commercial-electric-smart-led-downlight/

**Comment by w1ll1am23** [comment]
@henrikraken Can you see if this is working in the newest HomeAssistant release 0.27.0?

**Comment by xrolfex** [comment]
@w1ll1am23 @henrikraken This is currently working in the latest HomeAssitant release.

**Comment by w1ll1am23** [comment]
@xrolfex thanks for checking. @bradsk88, this can be closed.
