### ISSUE TITLE
Excessive API calls?

### ISSUE THREAD

**Issue by balloob** [python-wink/python-wink#42]
This is not so much an issue but more an FYI.

Home Assistant got an e-mail from a site reliability engineer at Wink about excessive API calls:

> We've observed 5 Wink users that have added the Home-Assistant.io integration to their account making excessive calls - roughly 8k every 10mins to the Wink API. 

I am not sure if this was because of the way Home Assistant used the API or that a bug sneaked in that causes the extra calls. From my knowledge of the Home Assistant integration, this high amount of calls would be highly unlikely.  @w1ll1am23 has migrated Home Assistant to use pubnub so we should drop usage significantly but I just thought to notify you that there might be an issue lingering somewhere.

**Comment by w1ll1am23** [comment]
@balloob, I assume you haven't heard anything else on this? I am thinking pubnub support fixed this. If you haven't heard anything else, I would say this can be closed.

**Comment by balloob** [comment]
Yep, haven't heard anything. Think indeed pubnub fixed this
