### ISSUE TITLE
Request to add Ring Doorbell for motion and button pressed

### ISSUE THREAD

**Issue by scadagenius** [python-wink/python-wink#65]
Is that possible to add support for Ring Doorbell? Json data from Wink shows details about this device I can provide Json if need and can do testing when needed. Once added would like to see this Wink component in Home Assistant as well.
Appreciate your efforts.

**Comment by w1ll1am23** [comment]
@scadaguru If you can provide the JSON that would be great. I can try to take a look.

**Comment by scadagenius** [comment]
Here it is the JSON from Wink hub poll. I have Ring Doorbell configured in Wink hub which receives motion and doorbell pressed events and Wink app shows notifications on cell phone, which means it gets updates from the Ring Doorbell so by subscribing to pubnub we can get those update and can have Home Assistant sensor reflect that status change and can be automated to do other stuff within HA system. To me looks like we can pull three key information: battery, motion and doorbell button pressed. Please let me know if you have any question. I have masked some sensitive information with xxxx. 

```
{
		"uuid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		"desired_state": {
			
		},
		"last_reading": {
			"battery": 1.0,
			"battery_updated_at": 1483588707.0458965,
			"motion": false,
			"motion_updated_at": 1483717738.8899395,
			"button_pressed": false,
			"button_pressed_updated_at": 1483658161.5844142,
			"motion_true": "N/A",
			"motion_true_updated_at": 1483717728.305417,
			"button_pressed_true": "N/A",
			"button_pressed_true_updated_at": 1483658092.2301679,
			"connection": true,
			"connection_updated_at": 1442873339.2134194,
			"last_recording_cuepoint_id": "1722851976",
			"last_recording_cuepoint_id_updated_at": 1483717787.6740644,
			"motion_changed_at": 1483717738.8899395,
			"motion_true_changed_at": 1483717728.305417,
			"button_pressed_changed_at": 1483658161.5844142,
			"button_pressed_true_changed_at": 1483658092.2301679,
			"battery_changed_at": 1483588707.0458965,
			"last_recording_cuepoint_id_changed_at": 1483717787.6740644
		},
		"subscription": {
			"pubnub": {
				"subscribe_key": "sub-c-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
				"channel": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|door_bell-xx|user-xxxxxx"
			}
		},
		"door_bell_id": "xx",
		"name": "Home",
		"locale": "en_us",
		"units": {
			
		},
		"created_at": 1442873339,
		"hidden_at": null,
		"capabilities": {
			"fields": [{
				"type": "percentage",
				"field": "battery",
				"mutability": "read-only"
			},
			{
				"type": "boolean",
				"field": "motion",
				"mutability": "read-only"
			},
			{
				"type": "boolean",
				"field": "button_pressed",
				"mutability": "read-only"
			}]
		},
		"user_ids": ["xxxxxx"],
		"manufacturer_device_model": "doorbell",
		"manufacturer_device_id": "12345",
		"device_manufacturer": "ring",
		"model_name": "Ring Video Doorbell",
		"upc_id": "xxx",
		"upc_code": "xxxxxxxxxxxx",
		"linked_service_id": "xxxxxx",
		"lat_lng": [xx.xxxxxx,
		-xx.xxxxxx],
		"location": "1234 Main St, City, ST XXXXX, USA"
	},

```

**Comment by w1ll1am23** [comment]
Sweet, I'll try to take a look tomorrow. Any idea the the difference between `motion` and `motion_true` is? I am assuming motion is the one reporting if motion was detected, since it is set to false. Just seems weird to have a motion_true field too.

**Comment by scadagenius** [comment]
Cool, not sure about motion_true and button_pressed_true. I can run some test to see if value changes from N/A. This component/sensors will be cool addition to Home Assistant if you can figure out, I can provide data and testing help if needed. Here is the website of the product www.ring.com, although manufacturer promised to provide API but not done yet. I am waiting to write custom software to locally capture video and data once API available. Thanks for really nice job for Wink component for Home Assistant.

**Comment by w1ll1am23** [comment]
Added in #67. Closing.
