### ISSUE TITLE
Exposing groups.

### ISSUE THREAD

**Issue by rbflurry** [python-wink/python-wink#83]
Is there any interest in exposing groups of lights to HA?

I could see some use cases to avoid multiple calls to turn a wink group of lights off.

But I could also see where it would create issues if we have HA groups and wink groups.

**Comment by w1ll1am23** [comment]
I have thought about adding them in the past and never did because of the fact that Home-Assistant has groups. Do you really think it would be beneficial other than the less API calls thing?

**Comment by rbflurry** [comment]
Honestly I am not sure about the benefits. I noticed a couple other platforms exposing groups which peaked my interest. At this time I would say No not worth it. At least in my use case.

https://github.com/home-assistant/home-assistant/pull/7376

https://github.com/home-assistant/home-assistant/pull/4744
