### ISSUE TITLE
Kidde Smoke detectors do not have battery level.

### ISSUE THREAD

**Issue by rbflurry** [python-wink/python-wink#94]
I am not sure when it started but I noticed the Kidde Smoke detectors do not show battery level in HASS anymore but they used to.

I can still see the info in the wink Json response.

Thanks as always.

**Comment by rbflurry** [comment]
@w1ll1am23 thank you again.

{
  "object_type": "smoke_detector",
  "object_id": "73142",
  "uuid": "54feac93-327e-4f04-a8ba-500c88e95245",
  "icon_id": null,
  "icon_code": null,
  "last_reading": {
    "connection": true,
    "connection_updated_at": 1462586187.9383092,
    "battery": 0.9,
    "battery_updated_at": 1506266794.7157471,
    "co_detected": false,
    "co_detected_updated_at": 1462586188.4449866,
    "smoke_detected": false,
    "smoke_detected_updated_at": 1471015253.2221863,
    "test_activated": false,
    "test_activated_updated_at": 1506267145.1675952,
    "battery_changed_at": 1506266794.7157471,
    "test_activated_changed_at": 1506267145.1675952
  },
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-eefe",
      "channel": "4a|smoke_detector-73142|user-338607"
    }
  },
  "smoke_detector_id": "73142",
  "name": "Hallway Smoke Detector",
  "locale": "en_us",
  "units": {},
  "created_at": 1462586187,
  "hidden_at": null,
  "capabilities": {},
  "manufacturer_device_model": "kidde_smoke_alarm",
  "manufacturer_device_id": null,
  "device_manufacturer": "kidde",
  "model_name": "Smoke Alarm",
  "upc_id": "524",
  "upc_code": "kidde_smoke_alarm",
  "primary_upc_code": "kidde_smoke_alarm",
  "hub_id": "249327",
  "local_id": null,
  "radio_type": "kidde",
  "linked_service_id": null,
  "lat_lng": [
    398519,
    -77867
  ],
  "location": "jjjjj"
}

**Comment by w1ll1am23** [comment]
This was an issue with Home Assistant not python-wink. Closing.
